import test from 'node:test';
import assert from 'node:assert/strict';
import {emptyState,fuelStats,mergeStates,reminderStatus,validateState,csvCell,addMonths,nextServiceDue} from '../core.js';
const fuel=(id,odometer,liters,full=true,missed=false)=>({id,date:'2026-10-01',type:'fuel',odometer,liters,full,missed});
test('full tank calculation excludes first fill and accumulates partial fills',()=>{const s=fuelStats([fuel('a',1000,40),fuel('b',1200,15,false),fuel('c',1500,25)]);assert.equal(s.kmL,12.5);assert.equal(s.l100,8);assert.equal(s.distance,500);});
test('single or partial fill cannot produce an economy estimate',()=>{assert.equal(fuelStats([fuel('a',1000,30)]).kmL,null);assert.equal(fuelStats([fuel('a',1000,30,false),fuel('b',1400,30)]).kmL,null);});
test('fuel expense without measured liters or odometer does not invent economy',()=>{
  const a={...fuel('a',1000,30),date:'2026-10-01'};
  const costOnly={...fuel('b',1000,0),date:'2026-10-02',cost:500,odometerEstimated:true};
  const c={...fuel('c',1500,40),date:'2026-10-03'};
  assert.equal(fuelStats([a,costOnly,c]).kmL,null);
  const state=emptyState();state.records.push({...costOnly,revision:'rev',updatedAt:1,vehicleId:'v'});
  assert.deepEqual(validateState(state),state);
});
test('missed fills reset the anchor',()=>{const s=fuelStats([fuel('a',1000,30),fuel('b',1400,35,true,true),fuel('c',1800,40)]);assert.equal(s.intervals.length,1);assert.equal(s.kmL,10);});
test('economy is weighted by distance and total fuel',()=>{const s=fuelStats([fuel('a',1000,30),fuel('b',1400,40),fuel('c',2000,30)]);assert.equal(s.kmL,1000/70);});
test('different vehicles are passed as isolated records and equal odometer is not estimated',()=>{assert.equal(fuelStats([fuel('a',1000,30),fuel('b',1000,30)]).kmL,null);});
test('cross-device merge is commutative, retains unrelated changes and deletion',()=>{const a=emptyState(),b=emptyState();a.records=[{id:'a',updatedAt:2,revision:'x'},{id:'c',updatedAt:1,revision:'old'}];b.records=[{id:'b',updatedAt:3,revision:'y'},{id:'c',updatedAt:4,revision:'new',deleted:true}];const merged=mergeStates(a,b);assert.equal(merged.records.length,3);assert.equal(merged.records.find(x=>x.id==='c').deleted,true);assert.deepEqual(mergeStates(a,b).records.sort((a,b)=>a.id.localeCompare(b.id)),mergeStates(b,a).records.sort((a,b)=>a.id.localeCompare(b.id)));});
test('revision gives deterministic tie-break and merge is idempotent',()=>{const a={...emptyState(),vehicles:[{id:'v',updatedAt:10,revision:'a'}]},b={...emptyState(),vehicles:[{id:'v',updatedAt:10,revision:'z'}]};assert.equal(mergeStates(a,b).vehicles[0].revision,'z');assert.deepEqual(mergeStates(b,b),b);});
test('reminders trigger on either date or mileage and respect completion',()=>{assert.equal(reminderStatus({dueDate:'2026-10-08',dueKm:100000},100,'2026-10-08'),'overdue');assert.equal(reminderStatus({dueDate:'2027-10-08',dueKm:1000},1001,'2026-10-08'),'overdue');assert.equal(reminderStatus({dueKm:2000},1100,'2026-10-08'),'soon');assert.equal(reminderStatus({dueDate:'2026-12-09'},0,'2026-10-08'),'normal');assert.equal(reminderStatus({done:true,dueKm:1},100,'2026-10-08'),'done');});
test('backup rejects unsupported and invalid data',()=>{assert.throws(()=>validateState({schema:2}));assert.throws(()=>validateState({...emptyState(),records:[{id:'r',revision:'a',updatedAt:1,type:'fuel',date:'2026-02-31',vehicleId:'v',cost:10,odometer:100,liters:0}]}));assert.deepEqual(validateState(emptyState()),emptyState());});
test('CSV escapes quotes and formula injection',()=>{assert.equal(csvCell('=1+1'),'"\'=1+1"');assert.equal(csvCell('a"b'),'"a""b"');});
test('service schedule respects calendar month ends and either due threshold',()=>{assert.equal(addMonths('2026-01-31',1),'2026-02-28');assert.deepEqual(nextServiceDue({date:'2026-01-31',odometer:75000,intervalMonths:6,intervalKm:10000}),{dueDate:'2026-07-31',dueKm:85000});assert.equal(reminderStatus({dueDate:'2026-07-31',dueKm:85000},85000,'2026-06-01'),'overdue');});
test('tax insurance and tire records validate as first-class entries',()=>{const state=emptyState();for(const type of ['tax','insurance','tire','inflation','battery'])state.records.push({id:type,revision:'rev',updatedAt:1,type,vehicleId:'v',date:'2026-10-08',cost:0,odometer:75000});assert.deepEqual(validateState(state),state);});
test('vehicle color and compressed photo survive backup validation',()=>{
  const state=emptyState();
  state.vehicles.push({id:'car2',revision:'rev',updatedAt:1,name:'第二台車',odometer:500,color:'blue',photo:'data:image/jpeg;base64,/9j/'});
  state.records.push({id:'reading',revision:'rev',updatedAt:2,type:'odometer',vehicleId:'car2',date:'2026-10-08',cost:0,odometer:900});
  assert.deepEqual(validateState(state),state);
  const sharpPhoto='data:image/jpeg;base64,'+'A'.repeat(250000);
  assert.deepEqual(validateState({...state,vehicles:[{...state.vehicles[0],photo:sharpPhoto}]}).vehicles[0].photo,sharpPhoto);
  assert.throws(()=>validateState({...state,vehicles:[{...state.vehicles[0],photo:'data:image/jpeg;base64,'+'A'.repeat(300000)}]}),/文字欄位過長/);
  assert.throws(()=>validateState({...state,vehicles:[{...state.vehicles[0],photo:'data:image/svg+xml;base64,AAAA'}]}),/圖片格式/);
});
